project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!blog.qmd"
    - "!archive.qmd"
    - "!posts/"
#
# Chose what to render - 
#https://quarto.org/docs/websites/index.html#render-targets

website:
  title: "Jason Selwyn"
  favicon: img/goby.png
  twitter-card: true
  open-graph: true
  site-url: https://jdselwyn.github.io
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: 'Research'
      - href: teach.qmd
        text: 'Teaching'
      # - href: consulting.qmd
      #   text: 'Consulting'
      # - text: Blog
      #   href: blog.qmd 
      - href: publications.qmd
        text: 'Publications'
      # - href: me.qmd
        # text: About Me
        
    right:
      # - text: Archive
      #   href: archive.qmd
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=3LC4ntQAAAAJ&hl=en 
      - icon: github
        href: https://github.com/jdselwyn
      - text: "{{< ai orcid >}}"
        href: https://orcid.org/0000-0002-9100-217X
      - text: "{{< ai cv >}}"
        href: documents/Jason%20Selwyn%20SP25%20CV.pdf
      - text: "{{< iconify ri bluesky-fill >}}"
        href: https://bsky.app/profile/jasonselwyn.bsky.social
      - icon: twitter
        href: https://www.twitter.com/jasonselwyn
      # - icon: rss
      #   href: blog.xml

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
