project:
  type: website
  output-dir: docs

website:
  title: "Jason Selwyn"
  favicon: img/goby.png
  twitter-card: true
  site-url: https://jdselwyn.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: 'Research'
      - href: teach.qmd
        text: 'Teaching'
      #- href: consulting.qmd
      #  text: 'Consulting'
      - href: publications.qmd
        text: 'Publications'
      - href: me.qmd
        text: About Me
        
    right:
      - text: "Google Scholar"
        href: https://scholar.google.com/citations?user=3LC4ntQAAAAJ&hl=en 
      - text: "GitHub"
        href: https://github.com/jdselwyn
      - text: "CV"
        href: documents/Jason%20Selwyn%20Sp23%20CV.pdf
      - text: "Twitter"
        href: https://www.twitter.com/jasonselwyn
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
