project:
  type: website
  output-dir: docs

website:
  title: "Jason Selwyn"
  favicon: img/goby.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: 'Research'
      - href: teach.qmd
        text: 'Teaching'
      - href: publications.qmd
        text: 'Publications'
      - href: me.qmd
        text: About Me
      - text: "Google Scholar"
        href: https://scholar.google.com/citations?user=3LC4ntQAAAAJ&hl=en 
      - text: "GitHub"
        href: https://github.com/jdselwyn
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
